### ISSUE TITLE
教育部辭典有腔口差的詞以「精確搜尋」會搜尋不到

### ISSUE THREAD

**Issue by sih4sing5hong5** [ChhoeTaigi/ChhoeTaigiWebsite#10]
`niáu-tshí`
![2018-10-30 9 12 50](https://user-images.githubusercontent.com/5996555/47720418-cc891900-dc88-11e8-9b83-b0083e672177.png)

**Comment by shiami** [comment]
@leowu2017 請補完lomaji_search_table搜尋功能。
