### ISSUE TITLE
 相關--ê 比 Kāng款--ê 重要

### ISSUE THREAD

**Issue by sih4sing5hong5** [ChhoeTaigi/ChhoeTaigiWebsite#12]
`Kāng款--ê` 較會查無詞
`相關--ê` 會查著tsit-thoo-la-khu的詞

一般來講，查著一堆會比查袂著好
建議預設是` 相關--ê `

**Comment by shiami** [comment]
Sú-iōng chêng-kéng bô-kâng, bô koh chhú-lí.
