### ISSUE TITLE
揣台語網站開講的小視窗

### ISSUE THREAD

**Issue by naphing** [ChhoeTaigi/ChhoeTaigiWebsite#14]
佇chrome介面無法度關開講的小視窗，
伊會擋著詞目欄[詳細]LINK，無法度揤，
揤FB爍爁符號仝款會跳出來
請檢查看覓是佗位的問題，勞力！
![default](https://user-images.githubusercontent.com/35830498/51666441-cb9e2400-1ff8-11e9-9fa2-24b7eacedba2.jpg)

**Comment by shiami** [comment]
Chiàⁿ-pêng téng-koân ē ū chhe-á.
