### ISSUE TITLE
g0v link broken

### ISSUE THREAD

**Issue by MrAwesome** [ChhoeTaigi/ChhoeTaigiWebsite#20]
The link to g0v is broken - instead of pointing to the g0v website it points here: https://chhoe.taigi.info/https://grants.g0v.tw/power/

That resolves to just https://chhoe.taigi.info, so the link is fully broken.

The offending code is here: https://github.com/ChhoeTaigi/ChhoeTaigiWebsite/blob/e6b97d94b651dee7accb7a2f7421b481966ec794/imports/ui/main/Footer.js#L96

I haven't used react-router before, but it looks like this is probably the solution: https://stackoverflow.com/a/62028885

Happy to put up a PR to fix this, just can't test it atm since I'm tethered.

**Comment by shiami** [comment]
Solution:
`<Link id='footer-image' to={{pathname:'https://grants.g0v.tw/power/'}} target='_blank' />`
