### ISSUE TITLE
「華文」一詞使用不當

### ISSUE THREAD

**Issue by Egnale99** [ChhoeTaigi/ChhoeTaigiWebsite#31]
我在貴站中發現多處「臺文」與「華文」的對立，然而此種用法並不妥當，於學術站不住腳。臺語屬於漢語，臺語之書寫體臺文屬於中文；而「華文」與「中文」同義。故不應將「華文」與「臺文」對立。我建議將「華文」改為「國文」、「官話文」等妥當且符合學術、現實的說法。

**Comment by shiami** [comment]
Khòaⁿ bô.

**Comment by TNTErick** [comment]
伊个意思是：「華文」只个詞、是中華个語言，亦着愛來指漢人个所有語言，甲「中」文共欵。不管咱各位个政治立場是按盞，總是咱所嚝个話確實是早前位唐山來个。咱若無愛用「國語」、「中文」，是因為「中文」去乎國民、共產黨提來專門指北京話，按呢「華語」會有「通好用來專門指北仔話」个感覺着是星馬二國華人个文化殖民唖。
我加忌个意見是台文用「台灣話、北仔話」，北仔話文用「台文、國文」。因為「語、文分開」本來嗎是中華政府帶入來个觀念。

Kiaⁿ lý iū-koh khòaⁿ bô, siá Pe̍h-ōe-jī hō͘ lý khòaⁿ:

I ê ì-sù sī kóng: "Hoa bûn" chit-ê sû, sī Tiong-hoa gý-giân, ma̍h tio̍h ài lâi chí Hàn-jîn ê só͘-ū gý-giân, kap "Tiong"-bûn kāng-khoán. M̄-koán lán kok-ūi chèng-tī li̍p-tiûⁿ sī án-chóaⁿ, chóng-sī lán só kóng ê ōe khak-si̍t sī chá-chêng ùi Tn̂g-soaⁿ lâi ê. Lán nā bô-ài iōng "Kok-gý," "Tiong-bûn" sī in-ūi "Tiong-bûn" khì hō͘ Kok-bîn-, Kiōng-sán-tóng thē-lâi choan-bûn chí Pak-kiaⁿ-ōe; án-né Hoa-gý ē ū "tang hó choan-bûn chí Pak-á-ōe" ê kám-kak tio̍h-sī Seng-ka-pho, Má-lâi-se-a nō-kok Hoa-jîn ê bûn-hòa si̍t-bîn ah.
Góa ka-kī ê ì-kiàn sī Tâi-bûn iōng "Tâi-oân-ōe, Pak-á-ōe;" Pak-á-ōe bûn iōng "台文、國文." In-ūi "gý, bûn" ê hun-pia̍t pún-lâi mā sī Tiong-hoa chèng-hú cha̍h-gi̍p-lâi ê koan-liām.
