### ISSUE TITLE
siòng e chhoe-tioh tsiòng

### ISSUE THREAD

**Issue by sih4sing5hong5** [ChhoeTaigi/ChhoeTaigiWebsite#6]
![2018-10-30 8 30 55](https://user-images.githubusercontent.com/5996555/47718227-d3ad2880-dc82-11e8-9e2d-2ce3ff451452.png)
![2018-10-30 8 31 05](https://user-images.githubusercontent.com/5996555/47718228-d3ad2880-dc82-11e8-8beb-60622f2d9d02.png)

**Comment by shiami** [comment]
@sih4sing5hong5 若chhōe相關--ê意思是內底有kauh chit-ê keyword，án-ne照程式結果是無問題。A̍h是你感覺使用上有無適合ê所在？

**Comment by sih4sing5hong5** [comment]
1. chhōe出有`siòng`的詞
2. chhōe出有`siòng`字串的詞

Chit-ma 程式是做2，毋過我會感覺1較tsiap用

**Comment by shiami** [comment]
Ref #12
