### ISSUE TITLE
正在找的時候，沒有正在搜尋的提示，直接顯示0筆

### ISSUE THREAD

**Issue by sih4sing5hong5** [ChhoeTaigi/ChhoeTaigiWebsite#7]
Chit-ma tng-tih chhoe e si, e hian-si `Chhōe ê結果：總共0份/0筆`
E tong-tsok chhoe-bo to li-khui.

**Comment by shiami** [comment]
@leowu2017 正在找的時候會顯示零筆，會被使用者當作找不到而離開。

看能否加上搜尋中的狀態顯示，以及起始狀態不要顯示0筆。

**Comment by shiami** [comment]
Cheng-ka tōng-thài tô͘-iūⁿ.
